language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true
    - python: nightly
      dist: xenial
      sudo: true
  allow_failures:
    - python: nightly
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true

install:
  - pip install poetry tox tox-travis

script:
  - tox

deploy:
  - provider: script
    script: poetry publish --username corollari --password $PYPI_PASS --build
    on:
      branch: master
      python: '3.7'
