language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      dist: xenial
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true
    - python: nightly
      dist: xenial
      sudo: true
  allow_failures:
    - python: nightly
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

install:
  - poetry install

script:
  - pytest
  - poetry build

deploy:
  - provider: script
    skip_cleanup: true
    script: poetry publish --username corollari --password $PYPI_PASS
    on:
      branch: master
      python: '3.7'
